POST http://localhost:3003/api/blogs
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5EIiwiaWQiOiI2NTJmZTE0OTcyYjA4MTZmNzEyZDkyYzIiLCJpYXQiOjE2OTc3MTgzMDR9.7Wvcn0ceD7TKnrQz5Wl9218ZbKLvhks3mvAtOYnwbGw

{
  "title": "Express is awesome!",
  "author": "John Doe",
  "url": "http://www.fakeblogaddress.com/post2",
  "likes": 12
}
