POST http://localhost:3003/api/blogs
Content-Type:  application/json
Authorization: ""

{
  "title": "Express is awesome!",
  "author": "John Doe",
  "url": "http://www.fakeblogaddress.com/post2",
  "likes": 12
}
